# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)
np.size(A)
np.shape(A)
A.dtype

print(np.size(A), np.shape(A), A.dtype)

15 (3, 5) int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [3]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [4]:
elementwise_substraction = B-C
print(elementwise_substraction)
print()
elementwise_multiplication = B*C
print(elementwise_multiplication)
print()
matrix_multiplication = B@C
print(matrix_multiplication)




[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [5]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
exponential_array = np.exp(B)

In [7]:
min_value= np.min(B)
print(min_value)


1


In [8]:
min_value_in_each_row = np.min(B,axis=1)
print(min_value_in_each_row)

[1 4 7]


In [9]:
min_value_in_each_column = np.min(B,axis=0)
print(min_value_in_each_column)

[1 2 3]


In [10]:
#Find the index value for the minimum value in the whole matrix (hint: use np.argmin)
min_value = np.argmin(B)
print(min_value)

0


In [11]:
# #Find the index value for the minimum value in each row (hint: use np.argmin)
# index_min_value_each_row = np.argmin(B,axis=1)
# print(index_min_value_each_row)

In [12]:
#Calculate the sum for all elements
sum = np.sum(B)
print(sum)

45


In [13]:
#Calculate the mean for each column. 
mean = np.mean(B)
print(mean)


5.0


In [14]:
#Calculate the median for each column. 
median = np.median(B)
print(median)

5.0


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [15]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


**Answer:**

In [16]:
A[1]

array([ 6,  7,  8,  9, 10])

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [17]:
A


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [19]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [20]:
#np.arange(30)-- display an array with 30 elements
#reshape (2,3,-1)-- this is used to reshape 30 elements to a 3 row 5 column matrix. Here 2 is refered to depth of the matrix.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [21]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [22]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [23]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [ ]:
def add_mult_matrices(A,B):
    

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [31]:
#Definera vektorn x enligt nedan. x= (4,3)
x=np.array([4,3])
x


array([4, 3])

In [33]:
#Vilken dimension har vektorn x
x.shape

(2,)

In [37]:
#beräkna 5x
y = 5*x
y

array([20, 15])

In [39]:
#beräkna 3x
z = 3*x
z

array([12,  9])

In [40]:
#beräkna 5x+3x
y+z


array([32, 24])

In [43]:
#beräkna 8x
8*x

array([32, 24])

In [44]:

#beräkna 4x-x
4*x-x

array([12,  9])

In [73]:
#beräkna x transpose
x = np.array([[4,3]])
k = x.T
print(k)
k.shape






[[4]
 [3]]


(2, 1)

In [76]:
#x+x^t definerat
#No as dimension for both vectors are not same we cant perform addition between them.

In [77]:
#beräkna ∣∣x∣∣

normen= np.linalg.norm(x)
normen

5.0

In [84]:
#definera vectorn v
v = np.array([[3],[7],[0],[11]])
v


array([[ 3],
       [ 7],
       [ 0],
       [11]])

In [85]:
v.shape

(4, 1)

In [86]:
#2v
2*v

array([[ 6],
       [14],
       [ 0],
       [22]])

In [87]:
#5v+2v
5*v+2*v

array([[21],
       [49],
       [ 0],
       [77]])

In [88]:
#4v-2v
4*v-2*v

array([[ 6],
       [14],
       [ 0],
       [22]])

In [95]:
#v transpose
v= np.array([[3],[7],[0],[11]])

m = v.T
print(m)
m.shape

[[ 3  7  0 11]]


(1, 4)

In [96]:
#∣∣v∣∣
normen_v= np.linalg.norm(v)
normen_v

13.379088160259652

In [99]:
v1= np.array([[4,3,1,5]])
v2 =np.array([[2,3,1,1]])
print(v1)
print(v2)

[[4 3 1 5]]
[[2 3 1 1]]


In [102]:
#∣∣v1∣∣
normen_v1 = np.linalg.norm(v1)
print(normen_v1)

7.14142842854285


In [103]:
#∣∣v1-v2∣∣ = normen_v1-normen_v2
normen_v2= np.linalg.norm(v2)
print(normen_v2)

normen_v1 - normen_v2



3.872983346207417


3.2684450823354334

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [114]:
#definera matriserna
A= np.matrix([[2,1,-1],[1,-1,1]])
print(A)
print()

B= np.matrix([[4,-2,1],[2,-4,-2]])
print(B)
print()

C = np.matrix([[1,2],[2,1]])
print(C)
print()

D = np.matrix([[3,4],[4,3]])
print(D)
print()

E= np.matrix([[1],[2]])
print(E)
print()

I = np.matrix([[1,0],[0,1]])
print(I)

[[ 2  1 -1]
 [ 1 -1  1]]

[[ 4 -2  1]
 [ 2 -4 -2]]

[[1 2]
 [2 1]]

[[3 4]
 [4 3]]

[[1]
 [2]]

[[1 0]
 [0 1]]


In [119]:
#2A
2*A


matrix([[ 4,  2, -2],
        [ 2, -2,  2]])

In [120]:
#B-2A
B-2*A

matrix([[ 0, -4,  3],
        [ 0, -2, -4]])

In [122]:
#2D-3C
2*D-3*C

matrix([[3, 2],
        [2, 3]])

In [126]:
#D^T

print(D.T)

D.T +2*D


[[3 4]
 [4 3]]


matrix([[ 9, 12],
        [12,  9]])

In [127]:
#2C^T -2D^T
2*(C.T) -2*(D.T)

matrix([[-4, -4],
        [-4, -4]])

In [148]:
#AC
AC= np.dot(A,C)
AC

matrix([[ 4,  7],
        [ 8, 14]])

In [145]:
#CD
CD = np.dot(C,D)
CD

matrix([[24, 25],
        [ 8,  6]])

In [149]:
#CB
CB= C@B
CB

matrix([[11, 13],
        [ 2,  6]])

In [151]:
#CI
CI = C@I
CI

matrix([[4, 3],
        [0, 2]])

In [154]:
#AB^T
B_T = B.T
print(B_T)

A@B_T

[[2 1]
 [1 3]]


matrix([[ 4,  7],
        [ 8, 14]])

In [135]:
#DEFINERA MATRISEN
A = np.array([[2,3,4],[5,4,1]])
print(A)

#AA^T
#not defined because of different dimensions

[[2 3 4]
 [5 4 1]]


In [159]:
#definera matriserna
A= np.matrix([[1,2],[2,4]])
B= np.matrix([[2,1],[1,3]])
C= np.matrix([[4,3],[0,2]])
print(A)
print(B)
print(C)

#AB=AC BNOT EQUAL TO C
AB=A@B
print(A@B)
AC=A@C
print(A@C)

print('AB=AC:',np.array_equal(AB,AC))
print('B!=C:',not np.array_equal(B,C))

[[1 2]
 [2 4]]
[[2 1]
 [1 3]]
[[4 3]
 [0 2]]
[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]
AB=AC: True
B!=C: True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [25]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [26]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [27]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
#v2 is a view of v1,if changes made to v2 will affect v1 also.By seeing the base attributes we can say view or copy. Here v2 is taking reference from v1.